# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-31 09:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('markers', '0003_auto_20180131_1203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='layerurl',
            name='name',
        ),
        migrations.DeleteModel(
            name='LayerName',
        ),
        migrations.DeleteModel(
            name='LayerUrl',
        ),
    ]
