# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-31 11:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LayerName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_text', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='LayerUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_text', models.CharField(max_length=128)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='layers.LayerName')),
            ],
        ),
    ]
