# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-07 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0003_auto_20180201_1056'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('typeOfGeom', models.CharField(max_length=255)),
                ('geometry', models.TextField()),
            ],
        ),
    ]
