# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-08 08:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0005_remove_feature_typeofgeom'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feature',
            old_name='geometry',
            new_name='coord',
        ),
        migrations.AddField(
            model_name='feature',
            name='geomType',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
