# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-26 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0007_feature_prop'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('source', models.TextField()),
                ('style', models.TextField()),
            ],
        ),
    ]
