# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-26 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0008_vector'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vector',
            name='source',
        ),
        migrations.RemoveField(
            model_name='vector',
            name='style',
        ),
        migrations.AddField(
            model_name='vector',
            name='alpha',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='vector',
            name='blue',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vector',
            name='green',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vector',
            name='radius',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='vector',
            name='red',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vector',
            name='width',
            field=models.FloatField(default=0),
        ),
    ]
